server:
  port: 5050
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: auth
          uri: http://localhost:1000/auth/
          predicates:
            - Path= /auth/**
            #==========================
        - id: feed
          uri: http://localhost:1001/feed/
          predicates:
            - Path= /feed/**
            #==========================
        - id: message
          uri: http://localhost:1002/message/
          predicates:
            - Path= /message/**
            #==========================
        - id: notificition
          uri: http://localhost:1003/notificition/
          predicates:
            - Path= /notificition/**
            #==========================
        - id: search
          uri: http://localhost:1004/search/
          predicates:
            - Path= /search/**
            #==========================

  application:
    name: gateway


  management:
    endpoint:
      gateway:
        enabled: true
    endpoints:
      web:
        exposure:
          include: gateway
