server:
  port: 1001
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: feed
  datasource:
    url: jdbc:mysql://localhost:3306/feed?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: devhub
    password: onuronuR3.
    hikari:
      connection-timeout: 3000000
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialet: org.hibernate.dialect.MySQL5Dialect

